import { Header } from "./components/Header";
import { Reveal } from "./components/Reveal";
import { DiagnosticExperience } from "./components/DiagnosticExperience";

const Arrow = () => <span className="arrow" aria-hidden="true">→︎</span>;
const solutions = [
  { tag: "CAPACITAR", name: "LinkedIn Revenue Mentoring", text: "Capacita líderes e equipes para gerar autoridade, conversas e oportunidades.", time: "7–14 dias", price: "R$ 1.997" },
  { tag: "GERAR DEMANDA", name: "LinkedIn Revenue Sprint", text: "Estrutura e implementa posicionamento, conteúdo, prospecção e cadências.", time: "7–14 dias", price: "R$ 2.997" },
  { tag: "ORGANIZAR", name: "Revenue Process Sprint", text: "Define pipeline, etapas, critérios, cadências e responsabilidades.", time: "7–14 dias" },
  { tag: "CENTRALIZAR", name: "Revenue CRM Sprint", text: "Implanta ou reorganiza o CRM como centro da operação.", time: "7–14 dias" },
  { tag: "ACELERAR", name: "AI Productivity Sprint", text: "Aplica IA de forma prática à produtividade comercial.", time: "7–14 dias" },
  { tag: "AUTOMATIZAR", name: "Automation Sprint", text: "Configura automações para tarefas repetitivas e conecta ferramentas críticas.", time: "7–14 dias" },
];
const comparison: [string, boolean, boolean, boolean, boolean][] = [["Agência", true, false, false, false], ["Consultoria", true, false, false, true], ["Software", false, false, true, false], ["Capacitação", false, false, false, true], ["VANT", true, true, true, true]];
const testimonials = [
  { quote: "Implantamos o método e, em 48h, meu closer parou de perder tempo com oportunidades sem fit. Hoje a triagem é automática, as oportunidades chegam classificadas por budget e a agenda é previsível. Nosso CAC caiu 40% no primeiro mês.", name: "Úrsula Aleixo", role: "PRESTO", solution: "Revenue Process Sprint + Automation Sprint", image: "/images/testimonials/ursula-aleixo-presto.webp" },
  { quote: "Com a estrutura de prospecção e o método da VANT, encontramos decisores que antes levávamos semanas para mapear. A operação de geração de demanda nos deu previsibilidade real — hoje sei exatamente quantas reuniões vou ter na semana.", name: "Julia Queiroz", role: "Head de Expansão — Grupo Morena Rosa", solution: "LinkedIn Revenue Sprint", image: "/images/testimonials/julia-queiroz-morena-rosa.jpg" },
  { quote: "O dashboard de gestão mudou tudo. Antes eu achava que a operação era rentável — agora eu provo com dados. O CRM ficou organizado, cada lead entra já classificado e o time comercial só foca em quem tem fit. Sem achismo, sem ruído.", name: "Cibelly", role: "DM2 — Franquias e Expansão", solution: "Revenue CRM Sprint + Revenue Intelligence Sprint", image: "/images/testimonials/cibelly-dm2.png" },
];

export default function Home() { return <main>
  <Header />
  <section id="inicio" className="hero section-dark"><div className="hero-image" aria-hidden="true" /><div className="grid-overlay" aria-hidden="true" /><div className="container hero-content"><div className="hero-copy"><span className="eyebrow"><i /> Growth Tech para operações comerciais</span><h1>Sua empresa não precisa de mais uma ação de marketing.<br/><em>Precisa de uma operação comercial que funcione.</em></h1><p>A VANT diagnostica os gargalos da sua operação comercial e implementa as soluções necessárias para corrigi-los — de aquisição e processo a CRM, automação e IA.</p><div className="button-row"><a className="button" href="#diagnostico">Diagnosticar minha operação <Arrow /></a><a className="button button-ghost" href="#solucoes">Conhecer as soluções</a></div></div><div className="hero-proof"><span>Diagnóstico</span><b /><span>Sprints 7–14 dias</span><b /><span>Implementação</span></div></div><a className="scroll-cue" href="#gargalos"><span>EXPLORE</span><i>↓</i></a></section>

  <section id="gargalos" className="section-dark section-pad gargalos"><div className="container"><Reveal className="section-heading wide"><span className="kicker">01 — O SINAL</span><h2>Se o crescimento depende de esforço demais, provavelmente existe um problema na <span>operação.</span></h2><p>O primeiro passo é identificar onde a operação perde oportunidades, tempo e capacidade de execução.</p></Reveal><div className="bottleneck-layout"><Reveal className="bottleneck-visual"><img src="/images/gargalos-operacao.webp" alt="Equipe analisando gargalos da operação comercial" loading="eager" fetchPriority="low" decoding="async" /><div className="signal-card"><strong>07</strong><span>GARGALOS<br/>RECORRENTES</span></div></Reveal><div className="issue-list">{["Poucas oportunidades", "Dependência de indicação", "Processo desorganizado", "CRM subutilizado", "Baixa conversão", "Atividades manuais", "IA sem aplicação prática"].map((item, i) => <Reveal key={item} className="issue"><span>0{i+1}</span><h3>{item}</h3><i>→︎</i></Reveal>)}</div></div></div></section>

  <section className="section-light section-pad thesis"><div className="container"><Reveal className="section-heading split-heading"><span className="kicker dark">02 — A TESE VANT</span><h2>O problema não está em uma ferramenta.<br/><span>Está na falta de uma operação funcionando como sistema.</span></h2></Reveal><Reveal className="thesis-stage"><div className="thesis-nodes">{["Aquisição", "Processo", "Pessoas", "Dados", "Tecnologia"].map(x => <div key={x}><i />{x}</div>)}</div><div className="converge-line"><span /></div><div className="system-core"><small>SISTEMA COMERCIAL</small><strong>VANT</strong><div>{["Aquisição", "Processo", "Pessoas", "Dados", "Tecnologia"].map(x => <span key={x}>{x}</span>)}</div></div></Reveal><Reveal className="thesis-close"><p>É isso que a VANT constrói.</p><span>Uma operação única. Mensurável. Escalável.</span></Reveal></div></section>

  <section id="metodo" className="section-dark section-pad method"><div className="container"><Reveal className="section-heading horizontal"><div><span className="kicker">03 — MÉTODO VANT</span><h2>Do gargalo à<br/><span>operação funcionando.</span></h2></div><p>Um caminho objetivo para transformar diagnóstico em execução — e execução na próxima evolução da operação.</p></Reveal><div className="method-grid">{[["01", "Diagnosticar", "Entendemos onde a operação perde eficiência, oportunidades e receita."], ["02", "Priorizar", "Identificamos os gargalos com maior impacto potencial."], ["03", "Implementar", "Executamos ciclos curtos para resolver problemas específicos."], ["04", "Evoluir", "Processos, dados e tecnologia passam a sustentar a próxima evolução da operação."]].map(([n,t,d]) => <Reveal key={n} className="method-step"><span>{n}</span><div className="method-icon">{n === "01" ? "◎" : n === "02" ? "◇" : n === "03" ? "△" : "→︎"}</div><h3>{t}</h3><p>{d}</p></Reveal>)}</div><div className="method-progress"><span>DIAGNÓSTICO</span><i/><span>PRIORIDADE</span><i/><span>SPRINT</span><i/><span>EVOLUÇÃO</span></div></div></section>

  <section id="score" className="section-light section-pad score-section"><div className="container score-layout"><Reveal className="score-copy"><span className="kicker dark">04 — VANT SCORE</span><h2>Antes de investir mais em crescimento, descubra onde sua operação está <span>perdendo oportunidades.</span></h2><p>Um diagnóstico executivo da maturidade comercial para transformar percepções dispersas em prioridades claras. Quando existe necessidade de implementação, o diagnóstico indica qual solução deve ser priorizada — do próximo Revenue Sprint à evolução para o VANT Revenue System.</p><ul><li>Diagnóstico completo</li><li>Mapa de gargalos</li><li>Prioridades definidas</li><li>Plano de ação</li></ul><div className="offer-line"><div><small>PRAZO</small><strong>7–14 dias</strong></div><div><small>INVESTIMENTO</small><strong>R$ 1.997</strong></div></div><a className="button" href="#diagnostico">Quero diagnosticar minha operação <Arrow /></a></Reveal><Reveal className="score-product"><img src="/images/score.jpg" alt="Interface executiva do VANT Score" loading="lazy" decoding="async" /><div className="score-float"><span>REVENUE SCORE</span><strong>72<small>/100</small></strong><p>Maturidade comercial</p></div></Reveal></div></section>

  <section id="solucoes" className="section-dark section-pad solutions-section"><div className="container"><Reveal className="section-heading horizontal"><div><span className="kicker">05 — SOLUÇÕES</span><h2>Escolha o problema que<br/>você precisa <span>resolver.</span></h2></div><p>Cada solução ataca um gargalo específico. Ciclos curtos, escopo claro e implementação real.</p></Reveal><div className="solutions-grid">{solutions.map((s, i) => <Reveal key={s.name} className={`solution-card ${i === 1 ? "featured" : ""}`}><div className="solution-top"><span>{s.tag}</span><i>0{i+1}</i></div><h3>{s.name}</h3><p>{s.text}</p><div className="solution-meta"><span>{s.time}</span>{s.price && <strong>{s.price}</strong>}</div><a href="#diagnostico">Conhecer solução <Arrow /></a></Reveal>)}</div></div></section>

  <section className="section-light section-pad paths linkedin-section"><div className="container"><Reveal className="section-heading centered"><span className="kicker dark">UMA FRENTE DA OPERAÇÃO</span><h2>LinkedIn dentro de uma operação comercial <span>mais estruturada.</span></h2><p>Na operação comercial, o LinkedIn pode cumprir um papel específico de posicionamento, demanda e relacionamento B2B.</p></Reveal><Reveal className="linkedin-visual"><img src="/images/linkedin-operation.webp" alt="Profissional analisando posicionamento e relacionamento comercial no LinkedIn" loading="lazy" decoding="async" /></Reveal><div className="linkedin-cards"><Reveal className="linkedin-card"><div className="linkedin-card-top"><span>APRENDER</span><i>01</i></div><h3>LinkedIn Revenue Mentoring</h3><p>Para empresas que querem desenvolver capacidade interna e operar o LinkedIn com método, consistência e autonomia.</p><small>Método · Acompanhamento · Capacitação</small><a href="#diagnostico">Conhecer a mentoria <Arrow /></a></Reveal><Reveal className="linkedin-card linkedin-card-featured"><div className="linkedin-card-top"><span>IMPLEMENTAR</span><i>02</i></div><h3>LinkedIn Revenue Sprint</h3><p>Para empresas que precisam estruturar e colocar em execução posicionamento, conteúdo, prospecção e cadências no LinkedIn.</p><small>Estrutura · Execução · Implementação</small><a href="#diagnostico">Conhecer o Sprint <Arrow /></a></Reveal></div><Reveal className="linkedin-close">Uma frente da operação. Um papel definido. Mais clareza para executar.</Reveal></div></section>

  <section className="section-dark sprint-feature"><div className="sprint-image" aria-hidden="true" /><div className="container sprint-copy"><Reveal><span className="kicker">06 — POR QUE SPRINTS</span><h2>Transformação comercial não precisa começar com projetos de <span>seis meses.</span></h2><p>A VANT trabalha com ciclos concentrados de 7 a 14 dias, atacando um gargalo específico por vez.</p><div className="sprint-flow">{["Problema", "Sprint", "Implementação", "Resultado", "Próxima evolução"].map((x,i)=><div key={x}><span>0{i+1}</span>{x}</div>)}</div><strong className="sprint-tagline">Menos projeto. Mais implementação. Evolução mais rápida.</strong></Reveal></div></section>

  <section id="cases" className="section-light section-pad cases"><div className="container"><Reveal className="section-heading horizontal cases-heading"><div><span className="kicker dark">CASES EM DESTAQUE</span><h2>Implementações reais para uma operação <span>mais assertiva.</span></h2></div><p>O que a VANT implementou em aquisição, CRM e automação — com clareza sobre o desafio e a frente aplicada.</p></Reveal><div className="cases-feature-grid">
    <Reveal className="case-feature case-feature-main"><div className="case-feature-top"><div><span className="case-eyebrow">CASE EM DESTAQUE</span><span className="case-client-logo case-client-logo-dm2"><img src="/images/cases/dm2.webp" alt="DM2" loading="lazy" /></span><span className="case-client-role">Franquias e Expansão</span></div><span className="case-feature-index">01</span></div><div className="case-feature-body"><div className="case-feature-copy"><span className="case-detail-label">DESAFIO</span><h3>Gerar mais oportunidades e melhorar a conversão do funil de franquias.</h3><p>Implementamos o método de LinkedIn para estruturar a geração de oportunidades e dar mais consistência à passagem entre conversas, agendamentos e reuniões.</p></div><div className="case-metrics" aria-label="Indicadores informados do case DM2"><div><strong>+25%</strong><span>Conversas</span></div><div><strong>+25%</strong><span>Agendamentos</span></div><div><strong>+25%</strong><span>Reuniões</span></div></div><div className="case-implementation"><span className="case-detail-label">IMPLEMENTAÇÃO VANT</span><strong>LinkedIn Revenue Sprint</strong></div></div></Reveal>
    <div className="cases-support-grid"><Reveal className="case-support-card"><div className="case-support-top"><div><span className="case-eyebrow">CASE 02</span><span className="case-client-logo case-client-logo-presto"><img src="/images/cases/presto.svg" alt="Presto" loading="lazy" /></span></div></div><span className="case-detail-label">DESAFIO</span><h3>Qualificar leads com menos trabalho manual.</h3><p>Implementamos e organizamos o CRM para reduzir o esforço operacional e melhorar a qualificação das oportunidades.</p><div className="case-implementation"><span className="case-detail-label">IMPLEMENTAÇÃO VANT</span><strong>Revenue CRM Sprint + Automation Sprint</strong></div></Reveal><Reveal className="case-support-card"><div className="case-support-top"><div><span className="case-eyebrow">CASE 03</span><span className="case-client-logo case-client-logo-3ck"><img src="/images/cases/3ck.webp" alt="3CK" loading="lazy" decoding="async" /></span></div></div><span className="case-detail-label">DESAFIO</span><h3>Conectar aquisição e gestão para ganhar assertividade.</h3><p>Unimos o método de LinkedIn à organização do CRM e às automações para coordenar a execução comercial.</p><div className="case-implementation"><span className="case-detail-label">IMPLEMENTAÇÃO VANT</span><strong>LinkedIn + CRM + Automação</strong></div></Reveal></div>
  </div><Reveal className="cases-outcome"><span>COMO A VANT ATUA</span><div><strong>Gargalo claro</strong><strong>Solução implementada</strong><strong>Próxima evolução</strong></div></Reveal></div></section>

  <section className="section-light section-pad testimonials"><div className="container"><Reveal className="section-heading horizontal testimonials-heading"><div><span className="kicker dark">DEPOIMENTOS</span><h2>A operação fala melhor quando existe <span>implementação.</span></h2></div><p>Relatos de clientes sobre como a VANT organiza processo, demanda e tecnologia dentro da operação comercial.</p></Reveal><div className="testimonials-grid">{testimonials.map(testimonial => <Reveal className="testimonial-card" key={testimonial.name}><div className="testimonial-card-top"><span className="testimonial-label">RELATO DE CLIENTE</span><span className="testimonial-quote-mark">“</span></div><blockquote>“{testimonial.quote}”</blockquote><div className="testimonial-author"><img src={testimonial.image} alt={testimonial.name} loading="lazy" decoding="async" /><div><strong>{testimonial.name}</strong><span>{testimonial.role}</span></div></div><small className="testimonial-solution">Solução VANT: {testimonial.solution}</small></Reveal>)}</div></div></section>

  <section className="section-dark audience"><div className="audience-image" aria-hidden="true" /><div className="container audience-content"><Reveal><span className="kicker">08 — PARA QUEM É</span><h2>Para empresas B2B que já possuem produto, mercado e operação comercial, mas encontraram gargalos para crescer com <span>mais previsibilidade.</span></h2><div className="audience-tags">{["B2B", "SaaS", "Tecnologia", "Consultorias", "Serviços", "Times comerciais", "Operações em crescimento"].map(x=><span key={x}>{x}</span>)}</div></Reveal></div></section>

  <section className="section-light section-pad difference"><div className="container"><Reveal className="section-heading centered"><span className="kicker dark">09 — MODELO INTEGRADO</span><h2>A VANT não é uma agência.<br/>Não é apenas consultoria. <span>Não é software.</span></h2></Reveal><Reveal className="comparison-wrap"><table><thead><tr><th>MODELO</th><th>ESTRATÉGIA</th><th>IMPLEMENTAÇÃO</th><th>TECNOLOGIA</th><th>CAPACITAÇÃO</th></tr></thead><tbody>{comparison.map(([name,...items]) => <tr key={name} className={name === "VANT" ? "vant-row" : ""}><th>{name}</th>{items.map((v,i)=><td key={i}><span className={v ? "yes" : "no"}>{v ? "✓" : "—"}</span></td>)}</tr>)}</tbody></table></Reveal><Reveal className="difference-close">Método, execução e tecnologia <span>dentro da mesma operação.</span></Reveal></div></section>

  <section id="sobre" className="section-dark about"><div className="about-image" aria-hidden="true" /><div className="container about-layout"><Reveal className="about-copy"><span className="kicker">10 — SOBRE A VANT</span><h2>Estamos construindo uma nova forma de implementar <span>crescimento comercial.</span></h2><p>A maioria das empresas precisa contratar diferentes fornecedores para resolver aquisição, processo, CRM, automação e tecnologia.</p><p>A VANT reúne essas competências em uma única operação de diagnóstico e implementação.</p><blockquote>Nosso objetivo não é entregar mais uma ação isolada. É fazer a operação comercial funcionar melhor.</blockquote></Reveal></div></section>

  <section id="diagnostico" className="final-cta section-dark"><div className="grid-overlay" aria-hidden="true" /><div className="network-lines" aria-hidden="true"><i/><i/><i/><i/></div><Reveal className="container final-content"><img src="/images/vant-symbol.webp" alt="" loading="lazy" decoding="async" /><span className="kicker">COMECE PELO DIAGNÓSTICO</span><h2>Antes de buscar mais leads, descubra o que está impedindo sua empresa de <span>crescer.</span></h2><p>VANT Score · Diagnóstico da operação · Plano priorizado · 7–14 dias<br/>Descubra o gargalo. Defina a prioridade. Escolha o próximo Sprint.</p><a className="button button-large" href="#diagnostico">Diagnosticar minha operação <Arrow /></a></Reveal></section>

  <DiagnosticExperience />

  <footer className="footer"><div className="container footer-main"><div className="footer-brand"><img src="/images/vant-logo.webp" alt="VANT" loading="lazy" decoding="async"/><p>Growth Tech para operações comerciais funcionais, mensuráveis e escaláveis.</p></div><div><strong>NAVEGUE</strong><a href="#solucoes">Soluções</a><a href="#score">VANT Score</a><a href="#metodo">Método</a><a href="#cases">Cases</a></div><div><strong>EMPRESA</strong><a href="#sobre">Sobre</a><a href="https://linkedin.com" target="_blank" rel="noreferrer">LinkedIn</a><a href="mailto:contato@v4nt.com.br">Contato</a></div></div><div className="container footer-bottom"><span>© 2026 VANT. Todos os direitos reservados.</span><span>Estratégia · Execução · Tecnologia</span></div></footer>
</main>; }
