import { Header } from "./components/Header";
import { Reveal } from "./components/Reveal";

const Arrow = () => <span className="arrow" aria-hidden="true">→︎</span>;
const solutions = [
  { tag: "CAPACITAR", name: "LinkedIn Revenue Mentoring", text: "Capacita líderes e equipes para gerar autoridade, conversas e oportunidades.", time: "7–14 dias", price: "R$ 1.997" },
  { tag: "GERAR DEMANDA", name: "LinkedIn Revenue Sprint", text: "Estrutura e implementa posicionamento, conteúdo, prospecção e cadências.", time: "7–14 dias", price: "R$ 2.997" },
  { tag: "ORGANIZAR", name: "Revenue Process Sprint", text: "Define pipeline, etapas, critérios, cadências e responsabilidades.", time: "7–14 dias" },
  { tag: "CENTRALIZAR", name: "Revenue CRM Sprint", text: "Implanta ou reorganiza o CRM como centro da operação.", time: "7–14 dias" },
  { tag: "ACELERAR", name: "AI Productivity Sprint", text: "Aplica IA de forma prática à produtividade comercial.", time: "7–14 dias" },
  { tag: "AUTOMATIZAR", name: "Automation Sprint", text: "Configura automações para tarefas repetitivas e conecta ferramentas críticas.", time: "7–14 dias" },
];
const comparison: [string, boolean, boolean, boolean, boolean][] = [["Agência", true, false, false, false], ["Consultoria", true, false, false, true], ["Software", false, false, true, false], ["Capacitação", false, false, false, true], ["VANT", true, true, true, true]];

export default function Home() { return <main>
  <Header />
  <section id="inicio" className="hero section-dark"><div className="hero-image" aria-hidden="true" /><div className="grid-overlay" aria-hidden="true" /><div className="container hero-content"><div className="hero-copy"><span className="eyebrow"><i /> Growth Tech para operações comerciais</span><h1>Sua empresa não precisa de mais uma ação de marketing.<br/><em>Precisa de uma operação comercial que funcione.</em></h1><p>A VANT diagnostica os gargalos da sua operação comercial e implementa as soluções necessárias para corrigi-los — de aquisição e processo a CRM, automação e IA.</p><div className="button-row"><a className="button" href="#diagnostico">Diagnosticar minha operação <Arrow /></a><a className="button button-ghost" href="#solucoes">Conhecer as soluções</a></div></div><div className="hero-proof"><span>Estratégia</span><b /><span>Execução</span><b /><span>Tecnologia</span></div></div><a className="scroll-cue" href="#gargalos"><span>EXPLORE</span><i>↓</i></a></section>

  <section id="gargalos" className="section-dark section-pad gargalos"><div className="container"><Reveal className="section-heading wide"><span className="kicker">01 — O SINAL</span><h2>Se o crescimento depende de esforço demais, provavelmente existe um problema na <span>operação.</span></h2><p>O primeiro passo é identificar onde a operação perde oportunidades, tempo e capacidade de execução.</p></Reveal><div className="bottleneck-layout"><Reveal className="bottleneck-visual"><img src="/images/gargalos-operacao.png" alt="Equipe analisando gargalos da operação comercial" loading="lazy" /><div className="signal-card"><strong>07</strong><span>GARGALOS<br/>RECORRENTES</span></div></Reveal><div className="issue-list">{["Poucas oportunidades", "Dependência de indicação", "Processo desorganizado", "CRM subutilizado", "Baixa conversão", "Atividades manuais", "IA sem aplicação prática"].map((item, i) => <Reveal key={item} className="issue"><span>0{i+1}</span><h3>{item}</h3><i>→︎</i></Reveal>)}</div></div></div></section>

  <section className="section-light section-pad thesis"><div className="container"><Reveal className="section-heading split-heading"><span className="kicker dark">02 — A TESE VANT</span><h2>O problema não está em uma ferramenta.<br/><span>Está na falta de uma operação funcionando como sistema.</span></h2></Reveal><Reveal className="thesis-stage"><div className="thesis-nodes">{["Aquisição", "Processo", "Pessoas", "Dados", "Tecnologia"].map(x => <div key={x}><i />{x}</div>)}</div><div className="converge-line"><span /></div><div className="system-core"><small>SISTEMA COMERCIAL</small><strong>VANT</strong><div>{["Aquisição", "Processo", "Pessoas", "Dados", "Tecnologia"].map(x => <span key={x}>{x}</span>)}</div></div></Reveal><Reveal className="thesis-close"><p>É isso que a VANT constrói.</p><span>Uma operação única. Mensurável. Escalável.</span></Reveal></div></section>

  <section id="metodo" className="section-dark section-pad method"><div className="container"><Reveal className="section-heading horizontal"><div><span className="kicker">03 — MÉTODO VANT</span><h2>Do gargalo à<br/><span>operação funcionando.</span></h2></div><p>Um caminho objetivo para transformar diagnóstico em execução — e execução na próxima evolução da operação.</p></Reveal><div className="method-grid">{[["01", "Diagnosticar", "Entendemos onde a operação perde eficiência, oportunidades e receita."], ["02", "Priorizar", "Identificamos os gargalos com maior impacto potencial."], ["03", "Implementar", "Executamos ciclos curtos para resolver problemas específicos."], ["04", "Evoluir", "Processos, dados e tecnologia passam a sustentar a próxima evolução da operação."]].map(([n,t,d]) => <Reveal key={n} className="method-step"><span>{n}</span><div className="method-icon">{n === "01" ? "◎" : n === "02" ? "◇" : n === "03" ? "△" : "→︎"}</div><h3>{t}</h3><p>{d}</p></Reveal>)}</div><div className="method-progress"><span>DIAGNÓSTICO</span><i/><span>PRIORIDADE</span><i/><span>SPRINT</span><i/><span>EVOLUÇÃO</span></div></div></section>

  <section id="score" className="section-light section-pad score-section"><div className="container score-layout"><Reveal className="score-copy"><span className="kicker dark">04 — VANT SCORE</span><h2>Antes de investir mais em crescimento, descubra onde sua operação está <span>perdendo oportunidades.</span></h2><p>Um diagnóstico executivo da maturidade comercial para transformar percepções dispersas em prioridades claras. Quando existe necessidade de implementação, o diagnóstico indica qual solução deve ser priorizada — do próximo Revenue Sprint à evolução para o VANT Revenue System.</p><ul><li>Diagnóstico completo</li><li>Mapa de gargalos</li><li>Prioridades definidas</li><li>Plano de ação</li></ul><div className="offer-line"><div><small>PRAZO</small><strong>7–14 dias</strong></div><div><small>INVESTIMENTO</small><strong>R$ 1.997</strong></div></div><a className="button" href="#diagnostico">Quero diagnosticar minha operação <Arrow /></a></Reveal><Reveal className="score-product"><img src="/images/score.jpg" alt="Interface executiva do VANT Score" loading="lazy" /><div className="score-float"><span>REVENUE SCORE</span><strong>72<small>/100</small></strong><p>Maturidade comercial</p></div></Reveal></div></section>

  <section id="solucoes" className="section-dark section-pad solutions-section"><div className="container"><Reveal className="section-heading horizontal"><div><span className="kicker">05 — SOLUÇÕES</span><h2>Escolha o problema que<br/>você precisa <span>resolver.</span></h2></div><p>Cada solução ataca um gargalo específico. Ciclos curtos, escopo claro e implementação real.</p></Reveal><div className="solutions-grid">{solutions.map((s, i) => <Reveal key={s.name} className={`solution-card ${i === 1 ? "featured" : ""}`}><div className="solution-top"><span>{s.tag}</span><i>0{i+1}</i></div><h3>{s.name}</h3><p>{s.text}</p><div className="solution-meta"><span>{s.time}</span>{s.price && <strong>{s.price}</strong>}</div><a href="#diagnostico">Conhecer solução <Arrow /></a></Reveal>)}</div></div></section>

  <section className="section-light section-pad paths"><div className="container"><Reveal className="section-heading centered"><span className="kicker dark">DOIS CAMINHOS</span><h2>Aprender ou <span>implementar?</span></h2><p>O objetivo é o mesmo. O nível de participação da VANT é o que muda.</p></Reveal><div className="path-grid"><Reveal className="path-card"><div className="path-image"><img src="/images/aprender-implementar.jpg" alt="Especialista e executivos construindo estratégia comercial" loading="lazy" /></div><div className="path-copy"><span>APRENDER</span><h3>LinkedIn Revenue Mentoring</h3><p>Mentoria + método + acompanhamento. Para construir capacidade interna com clareza e autonomia.</p><a href="#diagnostico">Conhecer a mentoria <Arrow /></a></div></Reveal><Reveal className="path-card implement"><div className="path-image"><img src="/images/solucoes.jpg" alt="Equipe implementando um sistema comercial" loading="lazy" /></div><div className="path-copy"><span>IMPLEMENTAR</span><h3>LinkedIn Revenue Sprint</h3><p>Estratégia + estrutura + execução. Para acelerar a construção da operação e colocar o método em prática.</p><a href="#diagnostico">Conhecer o sprint <Arrow /></a></div></Reveal></div></div></section>

  <section className="section-dark sprint-feature"><div className="sprint-image" aria-hidden="true" /><div className="container sprint-copy"><Reveal><span className="kicker">06 — POR QUE SPRINTS</span><h2>Transformação comercial não precisa começar com projetos de <span>seis meses.</span></h2><p>A VANT trabalha com ciclos concentrados de 7 a 14 dias, atacando um gargalo específico por vez.</p><div className="sprint-flow">{["Problema", "Sprint", "Implementação", "Resultado", "Próxima evolução"].map((x,i)=><div key={x}><span>0{i+1}</span>{x}</div>)}</div><strong className="sprint-tagline">Menos projeto. Mais implementação. Evolução mais rápida.</strong></Reveal></div></section>

  <section id="cases" className="section-light section-pad cases"><div className="container"><Reveal className="section-heading horizontal cases-heading"><div><span className="kicker dark">ONDE A VANT ATUA</span><h2>Diagnóstico e implementação para uma operação <span>mais coordenada.</span></h2></div><p>Três frentes em que a VANT organiza processo, demanda e tecnologia sem inventar métricas ou prometer resultados não comprovados.</p></Reveal><div className="cases-grid">
    <Reveal className="case-card"><div className="case-logo case-logo-dark"><img src="/images/cases/presto.svg" alt="Presto" loading="lazy" /></div><div className="case-card-copy"><span className="case-eyebrow">ESTRUTURA COMERCIAL</span><h3>Organizar oportunidades, prioridades e responsabilidades.</h3><p>A VANT atua na estruturação da operação, definindo rotina comercial, critérios e ritmo de execução.</p><ul><li>Clareza de processo</li><li>Prioridades</li><li>Ritmo de execução</li></ul></div></Reveal>
    <Reveal className="case-card"><div className="case-logo case-logo-light"><img src="/images/cases/cliente-lg85.webp" alt="Marca de empresa atendida pela VANT" loading="lazy" /></div><div className="case-card-copy"><span className="case-eyebrow">CRESCIMENTO B2B</span><h3>Coordenar aquisição, acompanhamento e tomada de decisão.</h3><p>A VANT estrutura a conexão entre demanda e operação para dar mais clareza ao acompanhamento comercial.</p><ul><li>Demanda</li><li>Acompanhamento</li><li>Visibilidade</li></ul></div></Reveal>
    <Reveal className="case-card"><div className="case-logo case-logo-light case-logo-3ck"><img src="/images/cases/3ck.png" alt="3CK" loading="lazy" /></div><div className="case-card-copy"><span className="case-eyebrow">TECNOLOGIA E ESCALA</span><h3>Organizar tecnologia para apoiar a execução comercial.</h3><p>A VANT estrutura processos, dados e tecnologia para apoiar uma rotina comercial mais integrada e executável.</p><ul><li>Processos</li><li>Execução</li><li>Capacidade</li></ul></div></Reveal>
  </div><Reveal className="cases-outcome"><span>O QUE A IMPLEMENTAÇÃO ORGANIZA</span><div><strong>Clareza de prioridades</strong><strong>Execução organizada</strong><strong>Capacidade de evolução</strong></div></Reveal></div></section>

  <section className="section-dark section-pad testimonials"><div className="container"><Reveal className="section-heading horizontal testimonials-heading"><div><span className="kicker">DEPOIMENTOS</span><h2>A operação fala melhor quando existe <span>implementação.</span></h2></div><p>Estamos reunindo relatos reais e autorizados de clientes para publicar experiências verificáveis, sem métricas ou promessas inventadas.</p></Reveal><Reveal className="testimonials-panel"><div className="testimonial-mark">“</div><div><span className="testimonial-label">RELATOS DE CLIENTES</span><p>Esta área será preenchida com depoimentos aprovados pelos clientes da VANT.</p><small>Diagnóstico, prioridade e implementação com contexto real.</small></div><a className="button button-ghost" href="mailto:contato@v4nt.com.br?subject=Quero compartilhar um depoimento">Compartilhar depoimento <Arrow /></a></Reveal></div></section>

  <section className="section-dark audience"><div className="audience-image" aria-hidden="true" /><div className="container audience-content"><Reveal><span className="kicker">08 — PARA QUEM É</span><h2>Para empresas B2B que já possuem produto, mercado e operação comercial, mas encontraram gargalos para crescer com <span>mais previsibilidade.</span></h2><div className="audience-tags">{["B2B", "SaaS", "Tecnologia", "Consultorias", "Serviços", "Times comerciais", "Operações em crescimento"].map(x=><span key={x}>{x}</span>)}</div></Reveal></div></section>

  <section className="section-light section-pad difference"><div className="container"><Reveal className="section-heading centered"><span className="kicker dark">09 — MODELO INTEGRADO</span><h2>A VANT não é uma agência.<br/>Não é apenas consultoria. <span>Não é software.</span></h2></Reveal><Reveal className="comparison-wrap"><table><thead><tr><th>MODELO</th><th>ESTRATÉGIA</th><th>IMPLEMENTAÇÃO</th><th>TECNOLOGIA</th><th>CAPACITAÇÃO</th></tr></thead><tbody>{comparison.map(([name,...items]) => <tr key={name} className={name === "VANT" ? "vant-row" : ""}><th>{name}</th>{items.map((v,i)=><td key={i}><span className={v ? "yes" : "no"}>{v ? "✓" : "—"}</span></td>)}</tr>)}</tbody></table></Reveal><Reveal className="difference-close">Método, execução e tecnologia <span>dentro da mesma operação.</span></Reveal></div></section>

  <section id="sobre" className="section-dark about"><div className="about-image" aria-hidden="true" /><div className="container about-layout"><Reveal className="about-copy"><span className="kicker">10 — SOBRE A VANT</span><h2>Estamos construindo uma nova forma de implementar <span>crescimento comercial.</span></h2><p>A maioria das empresas precisa contratar diferentes fornecedores para resolver aquisição, processo, CRM, automação e tecnologia.</p><p>A VANT reúne essas competências em uma única operação de diagnóstico e implementação.</p><blockquote>Nosso objetivo não é entregar mais uma ação isolada. É fazer a operação comercial funcionar melhor.</blockquote></Reveal></div></section>

  <section id="diagnostico" className="final-cta section-dark"><div className="grid-overlay" aria-hidden="true" /><div className="network-lines" aria-hidden="true"><i/><i/><i/><i/></div><Reveal className="container final-content"><img src="/images/vant-symbol.png" alt="" /><span className="kicker">COMECE PELO DIAGNÓSTICO</span><h2>Antes de buscar mais leads, descubra o que está impedindo sua empresa de <span>crescer.</span></h2><p>VANT Score · Diagnóstico da operação · Plano priorizado · 7–14 dias<br/>Descubra o gargalo. Defina a prioridade. Escolha o próximo Sprint.</p><a className="button button-large" href="mailto:contato@v4nt.com.br?subject=Quero diagnosticar minha operação">Diagnosticar minha operação <Arrow /></a></Reveal></section>

  <footer className="footer"><div className="container footer-main"><div className="footer-brand"><img src="/images/vant-logo.png" alt="VANT"/><p>Growth Tech para operações comerciais funcionais, mensuráveis e escaláveis.</p></div><div><strong>NAVEGUE</strong><a href="#solucoes">Soluções</a><a href="#score">VANT Score</a><a href="#metodo">Método</a><a href="#cases">Cases</a></div><div><strong>EMPRESA</strong><a href="#sobre">Sobre</a><a href="https://linkedin.com" target="_blank" rel="noreferrer">LinkedIn</a><a href="mailto:contato@v4nt.com.br">Contato</a></div></div><div className="container footer-bottom"><span>© 2026 VANT. Todos os direitos reservados.</span><span>Estratégia · Execução · Tecnologia</span></div></footer>
</main>; }
